/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.centroeducativo2.controladorDao.entidades.formularios;

import com.mycompany.centroeducativo2.controladorDao.AulaDaoImp;
import com.mycompany.centroeducativo2.controladorDao.CursoDaoImp;
import com.mycompany.centroeducativo2.controladorDao.PersonalDaoImp;
import com.mycompany.centroeducativo2.controladorDao.UnidadDaoImp;
import com.mycompany.centroeducativo2.controladorDao.entidades.Aula;
import com.mycompany.centroeducativo2.controladorDao.entidades.Curso;
import com.mycompany.centroeducativo2.controladorDao.entidades.Personal;
import com.mycompany.centroeducativo2.controladorDao.entidades.Unidad;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author sum27
 */
public class jpUnidad extends javax.swing.JPanel {

    public int idUnidad[];
    public int idCursoGlobal[];
    public int idTutorGlobal[];
    public int idAulaGlobal[];

    /**
     * Creates new form curso
     */
    public jpUnidad() {
        initComponents();
        configTabla();

        // Si la tabla esta vacia que pueda cargar
        if (cargaTabla() == true) {
            setCampos();
        }

        Ocultar();
    }

    private void Ocultar() {
        txtCodigo.setVisible(true);
        txtNombre.setVisible(true);
        txtAula.setVisible(true);
        txtTutor.setVisible(true);
        txtCurso.setVisible(true);
        txtObservaciones.setVisible(true);
        btnEditar.setVisible(true);

        btnAnadir.setVisible(false);
        btnActualizar.setVisible(false);
        btnCancelar.setVisible(false);
        btnBorrar.setVisible(false);
        CBOpciones.setVisible(false);
        CBTutor.setVisible(false);
        CBCurso.setVisible(false);
        CBAula.setVisible(false);
    }

    public void Mostrar() {
        txtCodigo.setVisible(false);
        txtNombre.setVisible(false);
        txtAula.setVisible(false);
        txtTutor.setVisible(false);
        txtCurso.setVisible(false);
        txtObservaciones.setVisible(false);
        btnEditar.setVisible(false);
        btnEditar.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTabla2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtCursoss = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        pnlDetalle = new javax.swing.JPanel();
        jlCodigo = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLNombre = new javax.swing.JLabel();
        btnBorrar = new javax.swing.JButton();
        btnAnadir = new javax.swing.JButton();
        CBOpciones = new javax.swing.JComboBox<>();
        btnEditar = new javax.swing.JButton();
        jLParentesco = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtObservaciones = new javax.swing.JTextField();
        jLCurso = new javax.swing.JLabel();
        txtCurso = new javax.swing.JTextField();
        jLAula = new javax.swing.JLabel();
        jLTutor1 = new javax.swing.JLabel();
        txtAula = new javax.swing.JTextField();
        txtTutor = new javax.swing.JTextField();
        CBTutor = new javax.swing.JComboBox<>();
        CBAula = new javax.swing.JComboBox<>();
        CBCurso = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTabla2.setBackground(new java.awt.Color(255, 255, 255));
        pnlTabla2.setForeground(new java.awt.Color(255, 255, 255));

        jtCursoss.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtCursoss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtCursosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jtCursoss);

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLabel4.setText("Buscar");

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout pnlTabla2Layout = new javax.swing.GroupLayout(pnlTabla2);
        pnlTabla2.setLayout(pnlTabla2Layout);
        pnlTabla2Layout.setHorizontalGroup(
            pnlTabla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabla2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlTabla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        pnlTabla2Layout.setVerticalGroup(
            pnlTabla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabla2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnlTabla2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        pnlDetalle.setBackground(new java.awt.Color(255, 255, 255));

        jlCodigo.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jlCodigo.setText("Codigo");

        btnActualizar.setBackground(new java.awt.Color(51, 255, 51));
        btnActualizar.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 51, 51));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLNombre.setBackground(new java.awt.Color(153, 255, 153));
        jLNombre.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLNombre.setText("Nombre");

        btnBorrar.setBackground(new java.awt.Color(51, 255, 51));
        btnBorrar.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnAnadir.setBackground(new java.awt.Color(51, 255, 51));
        btnAnadir.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        btnAnadir.setText("Añadir");
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });

        CBOpciones.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        CBOpciones.setForeground(new java.awt.Color(255, 51, 51));
        CBOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Añadir", "Actualizar", "Borrar" }));
        CBOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBOpcionesActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        btnEditar.setText("Realizar modificaciones");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLParentesco.setBackground(new java.awt.Color(153, 255, 153));
        jLParentesco.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLParentesco.setText("Observaciones");

        txtCodigo.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(153, 153, 153));

        txtNombre.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(153, 153, 153));

        txtObservaciones.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        txtObservaciones.setForeground(new java.awt.Color(153, 153, 153));

        jLCurso.setBackground(new java.awt.Color(153, 255, 153));
        jLCurso.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLCurso.setText("Curso");

        txtCurso.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        txtCurso.setForeground(new java.awt.Color(153, 153, 153));

        jLAula.setBackground(new java.awt.Color(153, 255, 153));
        jLAula.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLAula.setText("Aula");

        jLTutor1.setBackground(new java.awt.Color(153, 255, 153));
        jLTutor1.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLTutor1.setText("Tutor");

        txtAula.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        txtAula.setForeground(new java.awt.Color(153, 153, 153));

        txtTutor.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        txtTutor.setForeground(new java.awt.Color(153, 153, 153));

        CBTutor.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        CBTutor.setForeground(new java.awt.Color(153, 153, 153));

        CBAula.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        CBAula.setForeground(new java.awt.Color(153, 153, 153));

        CBCurso.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        CBCurso.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout pnlDetalleLayout = new javax.swing.GroupLayout(pnlDetalle);
        pnlDetalle.setLayout(pnlDetalleLayout);
        pnlDetalleLayout.setHorizontalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDetalleLayout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlDetalleLayout.createSequentialGroup()
                                .addComponent(CBOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlDetalleLayout.createSequentialGroup()
                                        .addGap(316, 316, 316)
                                        .addComponent(btnAnadir))
                                    .addGroup(pnlDetalleLayout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(btnEditar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnActualizar))))
                            .addGroup(pnlDetalleLayout.createSequentialGroup()
                                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jlCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCodigo)
                                        .addComponent(jLParentesco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlDetalleLayout.createSequentialGroup()
                                        .addComponent(jLCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(CBCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(120, 120, 120)
                                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAula, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlDetalleLayout.createSequentialGroup()
                                        .addComponent(jLAula, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CBAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlDetalleLayout.createSequentialGroup()
                                        .addComponent(jLTutor1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(CBTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnlDetalleLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBorrar))))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        pnlDetalleLayout.setVerticalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLParentesco)
                    .addComponent(CBTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTutor1))
                .addGap(18, 18, 18)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAula)
                    .addComponent(CBAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCurso)
                    .addComponent(CBCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(btnBorrar)
                .addGap(18, 18, 18)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(CBOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar))
                .addGap(18, 18, 18)
                .addComponent(btnAnadir)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        add(pnlDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 720, 610));
    }// </editor-fold>//GEN-END:initComponents
public boolean cargaTabla() {
        DefaultTableModel modelo = (DefaultTableModel) jtCursoss.getModel();

        UnidadDaoImp UnidadControler = UnidadDaoImp.getInstance();
        String[] fila = new String[6];

        modelo.setNumRows(0);
        try {
            List<Unidad> lst = UnidadControler.getAll();
            // Necesito guardar las id
            int cursos[] = new int[lst.size()];
            int tutores[] = new int[lst.size()];
            int aulas[] = new int[lst.size()];

            if (lst.size() > 0) {
                // Para borrar necesito el id
                idUnidad = new int[lst.size()];
                AulaDaoImp aul = AulaDaoImp.getInstance();
                CursoDaoImp cur = CursoDaoImp.getInstance();
                PersonalDaoImp per = PersonalDaoImp.getInstance();

                for (int i = 0; i < lst.size(); i++) {
                    fila[0] = "" + lst.get(i).getCodigo();
                    fila[1] = "" + lst.get(i).getNombre();
                    fila[2] = "" + lst.get(i).getObservaciones();
                    fila[3] = "" + cur.getById(lst.get(i).getIdcurso()).getNombre();
                    fila[4] = "" + per.getById(lst.get(i).getIdtutor()).getNombre();
                    fila[5] = "" + aul.getById(lst.get(i).getIdaula()).getCodigo();

                    modelo.addRow(fila);

                    // Le metemos el id
                    idUnidad[i] = lst.get(i).getId();
                    // Guardo la variable
                    cursos[i] = lst.get(i).getIdcurso();
                    tutores[i] = lst.get(i).getIdtutor();
                    aulas[i] = lst.get(i).getIdaula();
                }
                //selecciono la primera fila
                jtCursoss.setRowSelectionInterval(0, 0);
                return true;
            }
        } catch (Exception e) {
            System.out.println("Error:" + e.getMessage());
        }
        return false;
    }

    private Unidad getCampos() {
        Unidad c = new Unidad();
        c.setCodigo(txtCodigo.getText());
        c.setNombre(txtNombre.getText());
        c.setObservaciones(txtObservaciones.getText());
        c.setIdaula(idAulaGlobal[CBAula.getSelectedIndex()]);
        c.setIdcurso(idCursoGlobal[CBCurso.getSelectedIndex()]);
        c.setIdtutor(idTutorGlobal[CBTutor.getSelectedIndex()]);
        return c;
    }

    private Unidad AyudaActualizar() {
        Unidad cr = getCampos();
        cr.setId(idUnidad[Integer.parseInt(jtCursoss.getSelectedRow() + "")]);
        return cr;
    }

    public void setCampos() {
        txtCodigo.setText(jtCursoss.getValueAt(jtCursoss.getSelectedRow(), 0).toString());
        txtNombre.setText(jtCursoss.getValueAt(jtCursoss.getSelectedRow(), 1).toString());
        txtObservaciones.setText(jtCursoss.getValueAt(jtCursoss.getSelectedRow(), 2).toString());
        txtCurso.setText(jtCursoss.getValueAt(jtCursoss.getSelectedRow(), 3).toString());
        txtTutor.setText(jtCursoss.getValueAt(jtCursoss.getSelectedRow(), 4).toString());
        txtAula.setText(jtCursoss.getValueAt(jtCursoss.getSelectedRow(), 5).toString());

        btnEditar.setVisible(true);
    }

    public void configTabla() {
        String col[] = {"CODIGO", "NOMBRE", "OBSERVACIONES", "CURSO", "TUTOR", "AULA"};

        DefaultTableModel modelo = new DefaultTableModel(col, 0) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };

        jtCursoss.setModel(modelo);
        jtCursoss.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        //configuro evento valor cambiado...
/*        jtCursoss.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        public void valueChanged(ListSelectionEvent event) {
            System.out.println(jtCursoss.getValueAt(jtCursoss.getSelectedRow(), 0).toString());
            setCampos();
        }
    });
         */
    }
    private void jtCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCursosMouseClicked
        setCampos();
    }//GEN-LAST:event_jtCursosMouseClicked

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        /**
         * Un buscador
         */
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            DefaultTableModel modelo = (DefaultTableModel) jtCursoss.getModel();
            TableRowSorter<TableModel> trSorter = new TableRowSorter<TableModel>(modelo);

            jtCursoss.setRowSorter(trSorter);

            if (txtBuscar.getText().length() == 0) {
                trSorter.setRowFilter(null);
            } else {

                trSorter.setRowFilter(RowFilter.regexFilter(txtBuscar.getText().trim()));
            }

        }
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        CBOpciones.setVisible(true);
        btnEditar.setVisible(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        // Boton de añadir
        UnidadDaoImp c = UnidadDaoImp.getInstance();
        
        try {
            c.add(getCampos());
            JOptionPane.showMessageDialog(this, "Unidad agregado correctamente");
            cargaTabla();

        } catch (Exception e) {
            System.out.println("Error:" + e.getMessage());
        }
        Ocultar();
    }//GEN-LAST:event_btnAnadirActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        UnidadDaoImp c = UnidadDaoImp.getInstance();

        try {
            c.update(AyudaActualizar());
            JOptionPane.showMessageDialog(this, "Unidad actualizado");
            cargaTabla();

        } catch (Exception e) {
            System.out.println("Error:" + e.getMessage());
        }
        Ocultar();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        UnidadDaoImp c = UnidadDaoImp.getInstance();
        try {
            c.delete(idUnidad[Integer.parseInt((jtCursoss.getSelectedRow() + ""))]);
            JOptionPane.showMessageDialog(this, "Unidad borrado...");
            cargaTabla();

        } catch (Exception e) {
            System.out.println("Error:" + e.getMessage());
        }
        Ocultar();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Ocultar();
    }//GEN-LAST:event_btnCancelarActionPerformed
    private void cargarComboBox() {
        AulaDaoImp aul = AulaDaoImp.getInstance();
        CursoDaoImp curo = CursoDaoImp.getInstance();
        PersonalDaoImp pero = PersonalDaoImp.getInstance();
        try {
            int cont = 0;
            List<Curso> cursoLista = curo.getAll();
            idCursoGlobal = new int [cursoLista.size()];
            for (Curso cur : cursoLista) {
                CBCurso.addItem(cur.getCodigo());
                idCursoGlobal[cont] = cur.getId();
                cont++;
            }
            cont = 0;
            
            List<Aula> aulaLista = aul.getAll();
            idAulaGlobal = new int[cursoLista.size()];
            for (Aula al : aulaLista) {
                CBAula.addItem(al.getCodigo());
                idAulaGlobal[cont] = al.getId();
                cont++;
            }
            cont = 0;
            
            List<Personal> perLista = pero.getAll();
            idTutorGlobal = new int[perLista.size()];
            for (Personal per : perLista) {
                CBTutor.addItem(per.getNombre() + " " + per.getApellido1());
                idTutorGlobal[cont] = per.getId();
                cont++;
            }
        } catch (Exception e) {
            System.out.println("Error..." + e.getMessage());
        }
    }


    private void CBOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBOpcionesActionPerformed
        cargarComboBox();
        
        txtAula.setVisible(false);
        txtCurso.setVisible(false);
        txtTutor.setVisible(false);
        CBAula.setVisible(true);
        CBTutor.setVisible(true);
        CBCurso.setVisible(true);
        switch (CBOpciones.getSelectedIndex()) {
            case 0 -> {
                btnAnadir.setVisible(true);
                btnCancelar.setVisible(true);
            }
            case 1 -> {
                btnActualizar.setVisible(true);
                btnCancelar.setVisible(true);
            }
            case 2 -> {
                btnEditar.setVisible(false);
                btnBorrar.setVisible(true);
                btnCancelar.setVisible(true);
            }
        }
        CBOpciones.setVisible(false);
    }//GEN-LAST:event_CBOpcionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBAula;
    private javax.swing.JComboBox<String> CBCurso;
    private javax.swing.JComboBox<String> CBOpciones;
    private javax.swing.JComboBox<String> CBTutor;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JLabel jLAula;
    private javax.swing.JLabel jLCurso;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLParentesco;
    private javax.swing.JLabel jLTutor1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JTable jtCursoss;
    private javax.swing.JPanel pnlDetalle;
    private javax.swing.JPanel pnlTabla2;
    private javax.swing.JTextField txtAula;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtObservaciones;
    private javax.swing.JTextField txtTutor;
    // End of variables declaration//GEN-END:variables
}
