/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.centroeducativo2.controladorDao.entidades.formularios;

import com.mycompany.centroeducativo2.controladorDao.CursoAcademicoDaoImp;
import com.mycompany.centroeducativo2.controladorDao.entidades.CursoAcademico;
import java.awt.BorderLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButtonMenuItem;

/**
 *
 * @author sum27
 */
public class Main extends javax.swing.JFrame {
    public int idCursoAcademico=0; 
    private JLabel statusLabel;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        // Maximo de pantalla
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        JPanel status = new JPanel();
        statusLabel = new JLabel("");
        status.add( statusLabel );
        this.getContentPane().add(status, BorderLayout.SOUTH);
        
        generaMenuCursosAcademicos();
        //System.out.println("Generado menu");
        
    }
    
    private int generaMenuCursosAcademicos(){
        ButtonGroup bgrCursosAcademicos=new ButtonGroup();
        JRadioButtonMenuItem jrbCursoAcademico;
        
        CursoAcademicoDaoImp cursoaca=CursoAcademicoDaoImp.getInstance();
        
        try{
            List<CursoAcademico> lst=cursoaca.getAll();
            
                for( CursoAcademico curso :lst){
                    jrbCursoAcademico=new JRadioButtonMenuItem(""+curso.getDescripcion(), true);                    
                    jrbCursoAcademico.setName(""+curso.getId());
                    if (idCursoAcademico==0){
                        idCursoAcademico=curso.getId();
                        statusLabel.setText(""+curso.getDescripcion());
                    }
                    bgrCursosAcademicos.add(jrbCursoAcademico);
                    jmnCursoAcademico.add(jrbCursoAcademico); 
                    
                    jrbCursoAcademico.addItemListener(new ItemListener(){
                        /**
                         * Obtiene el curso seleccionado
                         */
                        public void itemStateChanged(ItemEvent e){
                            JRadioButtonMenuItem jrbSelected=(JRadioButtonMenuItem)e.getItem();
                            idCursoAcademico=Integer.parseInt(jrbSelected.getName());
                            System.out.println(""+idCursoAcademico);
                            statusLabel.setText(jrbSelected.getText());
                            
                        }
                    });
                }
                return idCursoAcademico;
        }catch(Exception e){
            System.out.println("Error..."+e.getMessage());
        }
        return 0;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        optmCursoAcademico = new javax.swing.JMenuItem();
        optmCurso = new javax.swing.JMenuItem();
        optmAlumno = new javax.swing.JMenuItem();
        optmAula = new javax.swing.JMenuItem();
        optmAutorizado = new javax.swing.JMenuItem();
        optmUnidades = new javax.swing.JMenuItem();
        jmnCursoAcademico = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        optmAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        getContentPane().add(content, java.awt.BorderLayout.CENTER);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Parametrización");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Mantenimimientos");
        editMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMenuMouseClicked(evt);
            }
        });

        optmCursoAcademico.setMnemonic('t');
        optmCursoAcademico.setText("Curso Academico");
        optmCursoAcademico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmCursoAcademicoActionPerformed(evt);
            }
        });
        editMenu.add(optmCursoAcademico);

        optmCurso.setMnemonic('y');
        optmCurso.setText("Curso");
        optmCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmCursooptmCursoActionPerformed(evt);
            }
        });
        editMenu.add(optmCurso);

        optmAlumno.setMnemonic('p');
        optmAlumno.setText("Alumno");
        optmAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmAlumnoActionPerformed(evt);
            }
        });
        editMenu.add(optmAlumno);

        optmAula.setText("Aula");
        optmAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmAulaActionPerformed(evt);
            }
        });
        editMenu.add(optmAula);

        optmAutorizado.setText("Autorizado");
        optmAutorizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmAutorizadoActionPerformed(evt);
            }
        });
        editMenu.add(optmAutorizado);

        optmUnidades.setText("Unidades");
        optmUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmUnidadesActionPerformed(evt);
            }
        });
        editMenu.add(optmUnidades);

        menuBar.add(editMenu);

        jmnCursoAcademico.setText("Año Academico");
        menuBar.add(jmnCursoAcademico);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        optmAcerca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        optmAcerca.setMnemonic('a');
        optmAcerca.setText("Acerca de");
        optmAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmAcercaActionPerformed(evt);
            }
        });
        helpMenu.add(optmAcerca);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void optmCursoAcademicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmCursoAcademicoActionPerformed
        jpCursoAcademico pnlcursoAca = new jpCursoAcademico();
        pnlcursoAca.setSize(this.getSize());
        pnlcursoAca.setLocation(0, 0);
        
        content.removeAll();
        content.add(pnlcursoAca,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_optmCursoAcademicoActionPerformed

    
    private void optmCursooptmCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmCursooptmCursoActionPerformed
        curso pnlcurso = new curso(idCursoAcademico);
        pnlcurso.setSize(this.getSize());
        pnlcurso.setLocation(0, 0);
        
        content.removeAll();
        content.add(pnlcurso,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_optmCursooptmCursoActionPerformed

    private void optmAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmAlumnoActionPerformed
        /**
         * Mostrar el panel de manera interna
         */
        jpAlumnos pnlAlumno = new jpAlumnos();
        pnlAlumno.setSize(this.getSize());
        pnlAlumno.setLocation(0, 0);
        
        content.removeAll();
        content.add(pnlAlumno,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_optmAlumnoActionPerformed

    private void optmUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmUnidadesActionPerformed
        frmUnidades2 unidades2=new frmUnidades2();
        /**
         * Mostrar el panel de manera interna
         */
        unidades2.setSize(638,375);
        unidades2.setLocation(0, 0);
        
        content.removeAll();
        content.add(unidades2,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_optmUnidadesActionPerformed

    private void editMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMenuMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_editMenuMouseClicked

    private void optmAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmAcercaActionPerformed
        // TODO add your handling code here:
        frmAcercaDeDialogo frmacerca=new frmAcercaDeDialogo(this, rootPaneCheckingEnabled);
        frmacerca.setVisible(true);

    }//GEN-LAST:event_optmAcercaActionPerformed

    private void optmAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmAulaActionPerformed
        /**
         * Mostrar el panel de manera interna
         */
        jpAula pnlAula = new jpAula();
        pnlAula.setSize(this.getSize());
        pnlAula.setLocation(0, 0);
        
        content.removeAll();
        content.add(pnlAula,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_optmAulaActionPerformed

    private void optmAutorizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmAutorizadoActionPerformed
        jpAutorizado pnlAutorizado = new jpAutorizado();
        pnlAutorizado.setSize(this.getSize());
        pnlAutorizado.setLocation(0, 0);
        
        content.removeAll();
        content.add(pnlAutorizado,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_optmAutorizadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jmnCursoAcademico;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem optmAcerca;
    private javax.swing.JMenuItem optmAlumno;
    private javax.swing.JMenuItem optmAula;
    private javax.swing.JMenuItem optmAutorizado;
    private javax.swing.JMenuItem optmCurso;
    private javax.swing.JMenuItem optmCursoAcademico;
    private javax.swing.JMenuItem optmUnidades;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables
}
